# Generated by Django 5.1.6 on 2025-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("serve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "time",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="时间",
                    ),
                ),
                ("id1", models.IntegerField(verbose_name="账号1")),
                ("id2", models.IntegerField(verbose_name="账号2")),
            ],
            options={
                "db_table": "Chat_Friend",
            },
        ),
        migrations.CreateModel(
            name="Friend2",
            fields=[
                (
                    "time",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="时间",
                    ),
                ),
                ("id1", models.IntegerField(verbose_name="账号1")),
                ("id2", models.IntegerField(verbose_name="账号2")),
            ],
            options={
                "db_table": "Chat_Friend2",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="账号"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="昵称")),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
            ],
            options={
                "db_table": "Chat_User",
            },
        ),
    ]
