# Generated by Django 5.1.6 on 2025-02-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Friend2",
        ),
    ]
