# Generated by Django 5.1.6 on 2025-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0003_delete_friend2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="time",
            field=models.AutoField(
                max_length=32, primary_key=True, serialize=False, verbose_name="时间"
            ),
        ),
    ]
