# Generated by Django 5.1.6 on 2025-02-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0007_alter_friend_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="time",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, verbose_name="时间"
            ),
        ),
    ]
