# Generated by Django 5.1.6 on 2025-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0009_alter_friend_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user1", models.CharField(max_length=32, verbose_name="用户一")),
                ("user2", models.CharField(max_length=32, verbose_name="用户二")),
                ("Message", models.CharField(max_length=128, verbose_name="消息")),
            ],
        ),
    ]
