# Generated by Django 5.1.6 on 2025-02-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0010_messages"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="messages",
            table="Chat_Message",
        ),
    ]
