# Generated by Django 5.1.6 on 2025-02-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0012_messages_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["time"]},
        ),
    ]
