# Generated by Django 5.1.6 on 2025-02-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0013_alter_messages_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="time",
            field=models.IntegerField(verbose_name="时间"),
        ),
    ]
