# Generated by Django 5.1.6 on 2025-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0014_alter_messages_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="time",
            field=models.BigIntegerField(verbose_name="时间"),
        ),
    ]
