# Generated by Django 5.1.6 on 2025-02-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0015_alter_messages_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="time",
            field=models.CharField(max_length=32, verbose_name="时间"),
        ),
    ]
