# Generated by Django 5.1.6 on 2025-02-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0016_alter_messages_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group_Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="聊天室名称")),
                ("user", models.CharField(max_length=32, verbose_name="发送人")),
                ("Message", models.CharField(max_length=128, verbose_name="消息")),
                ("time", models.CharField(max_length=32, verbose_name="时间")),
            ],
            options={
                "db_table": "Chat_Group_Message",
                "ordering": ["time"],
            },
        ),
        migrations.AlterModelTable(
            name="messages",
            table="Chat_Private_Message",
        ),
    ]
