# Generated by Django 5.1.6 on 2025-02-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0018_friend_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend_request",
            name="user1",
            field=models.CharField(max_length=32, verbose_name="用户1"),
        ),
        migrations.AlterField(
            model_name="friend_request",
            name="user2",
            field=models.CharField(max_length=32, verbose_name="用户2"),
        ),
    ]
